site: 찰리의 첫 제킬
url: https://bloggerHj.github.io
title: 드디어 첫 제킬 만들다
description: 블로그 만들기 프로젝트
twitter:
  username: 찰리
  card: 블로그

permalink: pretty

paginate: 1000
paginate_path: "/page:num/"
baseurl: ""

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

  - scope:
      path: "assets/images"
    values:
      image: true
